/* tslint:disable */
/* eslint-disable */
/**
 * Users API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddGroupCommandDto
 */
export interface AddGroupCommandDto {
    /**
     * 
     * @type {string}
     * @memberof AddGroupCommandDto
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof AddGroupCommandDto
     */
    trainerId: number;
}

/**
 * Check if a given object implements the AddGroupCommandDto interface.
 */
export function instanceOfAddGroupCommandDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "trainerId" in value;

    return isInstance;
}

export function AddGroupCommandDtoFromJSON(json: any): AddGroupCommandDto {
    return AddGroupCommandDtoFromJSONTyped(json, false);
}

export function AddGroupCommandDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddGroupCommandDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'trainerId': json['trainerId'],
    };
}

export function AddGroupCommandDtoToJSON(value?: AddGroupCommandDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'trainerId': value.trainerId,
    };
}

