/* tslint:disable */
/* eslint-disable */
/**
 * Users API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddRoleCommandDto
 */
export interface AddRoleCommandDto {
    /**
     * 
     * @type {string}
     * @memberof AddRoleCommandDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AddRoleCommandDto
     */
    description: string;
}

/**
 * Check if a given object implements the AddRoleCommandDto interface.
 */
export function instanceOfAddRoleCommandDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;

    return isInstance;
}

export function AddRoleCommandDtoFromJSON(json: any): AddRoleCommandDto {
    return AddRoleCommandDtoFromJSONTyped(json, false);
}

export function AddRoleCommandDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddRoleCommandDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
    };
}

export function AddRoleCommandDtoToJSON(value?: AddRoleCommandDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
    };
}

