/* tslint:disable */
/* eslint-disable */
/**
 * Users API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssignedGroupCommandDto
 */
export interface AssignedGroupCommandDto {
    /**
     * 
     * @type {number}
     * @memberof AssignedGroupCommandDto
     */
    groupId: number;
    /**
     * 
     * @type {number}
     * @memberof AssignedGroupCommandDto
     */
    userId: number;
}

/**
 * Check if a given object implements the AssignedGroupCommandDto interface.
 */
export function instanceOfAssignedGroupCommandDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "groupId" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function AssignedGroupCommandDtoFromJSON(json: any): AssignedGroupCommandDto {
    return AssignedGroupCommandDtoFromJSONTyped(json, false);
}

export function AssignedGroupCommandDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssignedGroupCommandDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'groupId': json['groupId'],
        'userId': json['userId'],
    };
}

export function AssignedGroupCommandDtoToJSON(value?: AssignedGroupCommandDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'groupId': value.groupId,
        'userId': value.userId,
    };
}

