/* tslint:disable */
/* eslint-disable */
/**
 * Users API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupMembersDto
 */
export interface GroupMembersDto {
    /**
     * 
     * @type {number}
     * @memberof GroupMembersDto
     */
    userId: number;
}

/**
 * Check if a given object implements the GroupMembersDto interface.
 */
export function instanceOfGroupMembersDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function GroupMembersDtoFromJSON(json: any): GroupMembersDto {
    return GroupMembersDtoFromJSONTyped(json, false);
}

export function GroupMembersDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupMembersDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['userId'],
    };
}

export function GroupMembersDtoToJSON(value?: GroupMembersDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
    };
}

