/* tslint:disable */
/* eslint-disable */
/**
 * Users API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SexTypeDto = {
    Mean: 'Mean',
    Woman: 'Woman'
} as const;
export type SexTypeDto = typeof SexTypeDto[keyof typeof SexTypeDto];


export function SexTypeDtoFromJSON(json: any): SexTypeDto {
    return SexTypeDtoFromJSONTyped(json, false);
}

export function SexTypeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SexTypeDto {
    return json as SexTypeDto;
}

export function SexTypeDtoToJSON(value?: SexTypeDto | null): any {
    return value as any;
}

