/* tslint:disable */
/* eslint-disable */
/**
 * Training API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TestDto
 */
export interface TestDto {
    /**
     * 
     * @type {string}
     * @memberof TestDto
     */
    identifier: string;
    /**
     * 
     * @type {number}
     * @memberof TestDto
     */
    vehicleId: number;
    /**
     * 
     * @type {string}
     * @memberof TestDto
     */
    text: string;
    /**
     * 
     * @type {string}
     * @memberof TestDto
     */
    time: string;
}

/**
 * Check if a given object implements the TestDto interface.
 */
export function instanceOfTestDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "identifier" in value;
    isInstance = isInstance && "vehicleId" in value;
    isInstance = isInstance && "text" in value;
    isInstance = isInstance && "time" in value;

    return isInstance;
}

export function TestDtoFromJSON(json: any): TestDto {
    return TestDtoFromJSONTyped(json, false);
}

export function TestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'identifier': json['identifier'],
        'vehicleId': json['vehicleId'],
        'text': json['text'],
        'time': json['time'],
    };
}

export function TestDtoToJSON(value?: TestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'identifier': value.identifier,
        'vehicleId': value.vehicleId,
        'text': value.text,
        'time': value.time,
    };
}

