/* tslint:disable */
/* eslint-disable */
/**
 * Users API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SexTypeDto } from './SexTypeDto';
import {
    SexTypeDtoFromJSON,
    SexTypeDtoFromJSONTyped,
    SexTypeDtoToJSON,
} from './SexTypeDto';

/**
 * 
 * @export
 * @interface UpdateUserCommandDto
 */
export interface UpdateUserCommandDto {
    /**
     * 
     * @type {number}
     * @memberof UpdateUserCommandDto
     */
    identifier: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserCommandDto
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserCommandDto
     */
    secondName: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserCommandDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserCommandDto
     */
    phone: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateUserCommandDto
     */
    weight: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateUserCommandDto
     */
    height: number;
    /**
     * 
     * @type {SexTypeDto}
     * @memberof UpdateUserCommandDto
     */
    sex: SexTypeDto;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserCommandDto
     */
    birthday: string;
}

/**
 * Check if a given object implements the UpdateUserCommandDto interface.
 */
export function instanceOfUpdateUserCommandDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "identifier" in value;
    isInstance = isInstance && "firstName" in value;
    isInstance = isInstance && "secondName" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "phone" in value;
    isInstance = isInstance && "weight" in value;
    isInstance = isInstance && "height" in value;
    isInstance = isInstance && "sex" in value;
    isInstance = isInstance && "birthday" in value;

    return isInstance;
}

export function UpdateUserCommandDtoFromJSON(json: any): UpdateUserCommandDto {
    return UpdateUserCommandDtoFromJSONTyped(json, false);
}

export function UpdateUserCommandDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserCommandDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'identifier': json['identifier'],
        'firstName': json['firstName'],
        'secondName': json['secondName'],
        'email': json['email'],
        'phone': json['phone'],
        'weight': json['weight'],
        'height': json['height'],
        'sex': SexTypeDtoFromJSON(json['sex']),
        'birthday': json['birthday'],
    };
}

export function UpdateUserCommandDtoToJSON(value?: UpdateUserCommandDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'identifier': value.identifier,
        'firstName': value.firstName,
        'secondName': value.secondName,
        'email': value.email,
        'phone': value.phone,
        'weight': value.weight,
        'height': value.height,
        'sex': SexTypeDtoToJSON(value.sex),
        'birthday': value.birthday,
    };
}

